/// Flutter icons FontIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FontIcons
///      fonts:
///       - asset: fonts/FontIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FontIcons {
  FontIcons._();

  static const _kFontFam = 'FontIcons';
  static const String? _kFontPkg = null;

  static const IconData mgb = IconData(0xe8b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mgh_lcs = IconData(0xe8f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
